// @ts-check
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { unified } from '@astrojs/markdown-remark';

import { padProxy } from './scripts/pad-proxy.mjs';
import { GUIDE_GROUPS } from './src/guides.mjs';
import remarkWidgetLinks from './src/plugins/remark-widget-links.mjs';

// Written by scripts/gen-widget-pages.mjs (part of `npm run generate`): the
// widget catalog's categories, in catalog order. Before the first generate,
// fall back to the flat autogenerated list.
const widgetSidebarFile = new URL('./src/widget-sidebar.json', import.meta.url);
const widgetGroups = existsSync(widgetSidebarFile)
  ? JSON.parse(readFileSync(widgetSidebarFile, 'utf8'))
  : null;

// Also written by gen-widget-pages.mjs: a page per showcase plus the overview.
// Listed here instead of autogenerated so the overview reads "All showcases",
// like the Guides and Widgets groups. The rest keep autogenerate's order
// (by slug) and their page titles.
const showcaseDir = new URL('./src/content/docs/showcases/', import.meta.url);
const showcasePages = existsSync(new URL('index.mdx', showcaseDir))
  ? readdirSync(showcaseDir)
      .filter((file) => /\.mdx?$/.test(file) && !/^index\.mdx?$/.test(file))
      .map((file) => `showcases/${file.replace(/\.mdx?$/, '')}`)
      .sort((a, b) => a.localeCompare(b))
  : null;

const repo = 'https://github.com/danReynolds/fleury';

const site = 'https://danreynolds.github.io';
const base = '/fleury';
const asset = (path) => `${base}/${path}`;

// https://astro.build/config
export default defineConfig({
  site,
  base,
  markdown: {
    processor: unified({ remarkPlugins: [[remarkWidgetLinks, { base }]] }),
  },
  vite: padProxy(process.env.FLEURY_PAD_PROXY_TARGET),
  integrations: [
    starlight({
      title: 'Fleury',
      description:
        'A retained-mode UI framework for the terminal — and the browser.',
      // The product mark: leaf-F shown next to the wordmark in the header.
      logo: {
        src: './src/assets/fleury-icon.png',
        alt: 'Fleury',
      },
      social: [{ icon: 'github', label: 'GitHub', href: repo }],
      // "Edit page" opens the page's file under website/. A generated,
      // gitignored page must set `editUrl` itself, to its real source or to
      // false (synced architecture docs point at docs/; see sync-docs.mjs).
      editLink: { baseUrl: `${repo}/edit/main/website/` },
      // Primary favicon is the scalable SVG; the rest (ICO fallback, PNG sizes,
      // apple-touch, PWA manifest, social card) are added via head below.
      // Starlight adds Astro's configured base path to this public asset.
      favicon: '/favicon.svg',
      head: [
        { tag: 'link', attrs: { rel: 'icon', href: asset('favicon.ico'), sizes: '32x32' } },
        { tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '32x32', href: asset('favicon-32.png') } },
        { tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '16x16', href: asset('favicon-16.png') } },
        { tag: 'link', attrs: { rel: 'apple-touch-icon', sizes: '180x180', href: asset('apple-touch-icon.png') } },
        { tag: 'link', attrs: { rel: 'manifest', href: asset('site.webmanifest') } },
        { tag: 'meta', attrs: { name: 'theme-color', content: '#070d0b' } },
        { tag: 'meta', attrs: { property: 'og:image', content: `${site}${asset('og.png')}` } },
        { tag: 'meta', attrs: { property: 'og:image:width', content: '1200' } },
        { tag: 'meta', attrs: { property: 'og:image:height', content: '630' } },
        { tag: 'meta', attrs: { name: 'twitter:card', content: 'summary_large_image' } },
        { tag: 'meta', attrs: { name: 'twitter:image', content: `${site}${asset('og.png')}` } },
        // Starlight restores the sidebar's scroll position only when you
        // navigate within the site. Arriving from search or a link, a page deep
        // in the sidebar (most widget pages) starts scrolled to the top with
        // its own entry out of view. A module script runs after Starlight's
        // restore, so it only moves the sidebar when the entry is still hidden.
        // It checks again on load: the dev server applies styles from scripts,
        // so the pane may not scroll yet when this first runs.
        {
          tag: 'script',
          attrs: { type: 'module' },
          content: `const reveal = () => {
  const pane = document.getElementById('starlight__sidebar');
  const current = pane?.querySelector('[aria-current="page"]');
  if (!pane || !current || !matchMedia('(min-width: 50em)').matches) return;
  const view = pane.getBoundingClientRect();
  const item = current.getBoundingClientRect();
  if (item.top < view.top || item.bottom > view.bottom) {
    pane.scrollTop += item.top - view.top - view.height / 3;
  }
};
reveal();
if (document.readyState !== 'complete') addEventListener('load', reveal, { once: true });`,
        },
      ],
      // Drop the per-page table-of-contents site-wide; content goes full-width
      // (see the .sl-container override in fleury.css).
      tableOfContents: false,
      components: {
        TwoColumnContent: './src/components/DocsContent.astro',
        SiteTitle: './src/components/DocsSiteTitle.astro',
      },
      // Shared styling for embedded Fleury examples — must be site-wide so the
      // JS-created fullscreen overlay (appended to <body>, outside component
      // scope) and the knob pages get the same host font metrics + chrome.
      customCss: [
        '@fontsource-variable/space-grotesk',
        './src/styles/fleury.css',
      ],
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'Introduction', slug: 'introduction' },
            { label: 'Fleury Pad', slug: 'pad' },
            { label: 'Getting started', slug: 'getting-started' },
            { label: 'Tutorial: a filterable list', slug: 'tutorial' },
            { label: 'Coming from Flutter', slug: 'coming-from-flutter' },
            { label: 'Why Fleury', slug: 'comparison' },
          ],
        },
        {
          label: 'Core concepts',
          items: [
            { label: 'Widgets & state', slug: 'concepts/widgets-and-state' },
            { label: 'App entry points', slug: 'concepts/app-entry' },
          ],
        },
        {
          label: 'Guides',
          items: [
            { label: 'All guides', slug: 'guides' },
            ...GUIDE_GROUPS.map((group) => ({
              label: group.label,
              items: group.items,
            })),
          ],
        },
        {
          label: 'Architecture',
          items: [
            { label: 'Architecture overview', slug: 'architecture/overview' },
            { label: 'Deep dive', slug: 'architecture/deep-dive' },
            { label: 'Core and targets', slug: 'architecture/core-and-targets' },
            {
              label: 'Serving and embedding',
              slug: 'architecture/serving-and-embedding',
            },
            {
              label: 'Built for agents',
              slug: 'architecture/agents-and-semantics',
            },
            { label: 'Performance', slug: 'architecture/performance' },
          ],
        },
        {
          label: 'Widgets',
          items: widgetGroups
            ? [
                { label: 'All widgets', slug: 'widgets' },
                // Collapsed by default; Starlight opens the group holding the
                // current page.
                ...widgetGroups.map((group) => ({
                  label: group.label,
                  collapsed: true,
                  items: group.items,
                })),
              ]
            : [{ autogenerate: { directory: 'widgets' } }],
        },
        {
          label: 'Showcases',
          collapsed: true,
          items: showcasePages
            ? [{ label: 'All showcases', slug: 'showcases' }, ...showcasePages]
            : [{ autogenerate: { directory: 'showcases' } }],
        },
      ],
    }),
  ],
});
